# Function to organize order of endogenous constructs from most exogenous forwards
construct_order <- function(smMatrix) {
  depends_on <- function(latents) {
    ret <- c()
    for (latent in latents) {
      ret <- c(ret,smMatrix[smMatrix[,"source"] == c(latent), "target"])
    }
    unique(ret)
  }

  has_score <- function(latents, list) {
    ret <- c()
    for (latent in latents) {
      next_val <- all(smMatrix[smMatrix[,"target"]==latent,"source"] %in% list)
      ret <- c(ret,next_val)
    }
    ret
  }

  # get purely endogenous and purely exogenous
  only_endogenous <- setdiff(unique(smMatrix[,2]), unique(smMatrix[,1]))
  only_exogenous <- setdiff(unique(smMatrix[,1]), unique(smMatrix[,2]))
  # get ltVariables
  ltVariables <- unique(c(smMatrix[,1],smMatrix[,2]))

  exogenous_latent <- setdiff(ltVariables, only_endogenous)
  scores_list <- only_exogenous
  while (!setequal(exogenous_latent,scores_list)) {
    scores_list <- c(scores_list,setdiff(depends_on(scores_list)[has_score(depends_on(scores_list), scores_list)], scores_list))
  }

  final_list <- setdiff(scores_list,only_exogenous)

return(c(final_list,only_endogenous))

}

#' Predictive Scheme
#'
#' \code{predict_EA} and \code{predict_DA} specify the predictive scheme to be used in the generation of the
#' predictions. EA refers to Earliest Antecedents nad DA to Direct Antecedents.
#'
#' @param smMatrix is the \code{structural_model} - a source-to-target matrix representing the inner/structural model,
#'  generated by \code{relationships} generated by SEMinR.
#'
#' @param path_coef is the Path Coefficients matrix from a SEMinR model.
#'
#' @param construct_scores is the matrix of construct scores generated by SEMinR.
#'
#' @usage
#'  predict_EA(smMatrix, path_coef, construct_scores)
#'
#' @export
predict_EA <- function(smMatrix, path_coef, construct_scores) {
  order <- construct_order(smMatrix)
  only_exogenous <- setdiff(unique(smMatrix[,1]), unique(smMatrix[,2]))
  return_matrix <- construct_scores
  return_matrix[,setdiff(colnames(return_matrix),only_exogenous)] <- 0
  for (latent in order) {
    return_matrix[,latent] <- return_matrix %*% path_coef[,latent]

  }
 return(return_matrix)
}

#' Predictive Scheme
#'
#' \code{predict_EA} and \code{predict_DA} specify the predictive scheme to be used in the generation of the
#' predictions. EA refers to Earliest Antecedents nad DA to Direct Antecedents.
#'
#' @param smMatrix is the \code{structural_model} - a source-to-target matrix representing the inner/structural model,
#'  generated by \code{relationships} generated by SEMinR.
#'
#' @param path_coef is the Path Coefficients matrix from a SEMinR model.
#'
#' @param construct_scores is the matrix of construct scores generated by SEMinR.
#'
#' @usage
#'  predict_DA(smMatrix, path_coef, construct_scores)
#'
#' @export
predict_DA <- function(smMatrix, path_coef, construct_scores) {
  only_exogenous <- setdiff(unique(smMatrix[,1]), unique(smMatrix[,2]))
  return_matrix <- construct_scores%*%path_coef
  return_matrix[,only_exogenous] <- construct_scores[,only_exogenous]
  return(return_matrix)
}
