#' PLSpredict performs predictions on SEMinR PLS models
#'
#' \code{PLSpredict} performs predictions on PLS models generated by SEMinR.
#'
#' This function performs construct and item level predictions
#'
#' @param model A SEMinR model that has been trained on the training data
#'
#' @param testData The testing data for which predictions will be generated
#'
#' @param technique The predictive technique to be employed, Earliest Antecedents (EA) \code{predict_EA} or
#' Direct Antecedents (DA) \code{predict_DA}
#'
#' @usage
#'
#' PLSpredict(model, testData, technique)
#'
#' @examples
#' library(seminr)
#' data(mobi)
#' trainData <- mobi[1:200,]
#' testData <- mobi[201:250,]
#'
#' # seminr syntax for creating measurement model
#' mobi_mm <- constructs(
#'   composite("Image",        multi_items("IMAG", 1:5)),
#'   composite("Expectation",  multi_items("CUEX", 1:3)),
#'   composite("Value",        multi_items("PERV", 1:2)),
#'   composite("Satisfaction", multi_items("CUSA", 1:3))
#' )
#'
#' mobi_sm <- relationships(
#'   paths(to = "Satisfaction",
#'         from = c("Image", "Expectation", "Value"))
#' )
#'
#' mobi_train <- estimate_pls(trainData, mobi_mm, interactions = NULL, mobi_sm)
#' predictions <- PLSpredict(mobi_train, testData)
#'
#' @export
PLSpredict <- function(model, testData, technique = predict_DA){

  #Extract Measurements needed for Predictions
  normData <- testData[,model$mmVariables]

  #Normalize data
  normData[,model$mmVariables] <- t(t(sweep(normData[,model$mmVariables],2,model$meanData[model$mmVariables])) / model$sdData[model$mmVariables])

  #Convert dataset to matrix
  normData<-data.matrix(normData)

  #Estimate Factor Scores from Outter Path
  construct_scores <- normData%*%model$outer_weights

  #Estimate Factor Scores from Inner Path and complete Matrix
  construct_scores <- technique(model$smMatrix, model$path_coef, construct_scores)

  #Predict Measurements with loadings
  predictedMeasurements<-construct_scores%*% t(model$outer_loadings)

  #Denormalize data
  predictedMeasurements[,model$mmVariables] <- sweep((predictedMeasurements[,model$mmVariables] %*% diag(model$sdData[model$mmVariables])),2,model$meanData[model$mmVariables],"+")

  #Calculating the residuals
  residuals <- testData[,model$mmVariables] - predictedMeasurements[,model$mmVariables]

  #Prepare return Object
  predictResults <- list(testData = testData[,model$mmVariables],
                         predicted_Measurements = predictedMeasurements[,model$mmVariables],
                         residuals = residuals,
                         predicted_CompositeScores = construct_scores)

  class(predictResults) <- "predictResults"
  return(predictResults)
}
